### ISSUE TITLE
Runtime exception when trying to configure to send logs to OpenTelemetry collector

### ISSUE THREAD

**Issue by sharifmamun** [serilog/serilog-sinks-opentelemetry#121]
I have a class like this:

```
        public static IHostBuilder UseSerilog(this IHostBuilder hostBuilder)
        {
            Serilog.Debugging.SelfLog.Enable(Console.Error);

            return hostBuilder.UseSerilog((hostBuilderContext, loggerConfiguration) =>
            {
                // Here we configure host Serilog logger.

                loggerConfiguration
                    // Logger configuration is read from host configuration (typically, "Serilog" section in appsettings.json file).
                    .ReadFrom.Configuration(hostBuilderContext.Configuration, new ConfigurationReaderOptions(DependencyContext.Default))
                    .Enrich.With<HostContextEnricher>()
                    .WriteTo.OpenTelemetry(options =>
                    {
                        options.ResourceAttributes = new Dictionary<string, object>
                        {
                            ["service.name"] = "test-logging-service",
                            ["index"] = 10,
                            ["flag"] = true,
                            ["value"] = 3.14
                        };

                        options.Endpoint = "http://localhost:4318/v1/logs";
                        options.Protocol = OtlpProtocol.HttpProtobuf;

                        // Prevent tracing of outbound requests from the sink
                        options.HttpMessageHandler = new SocketsHttpHandler { ActivityHeadersPropagator = null };

                        options.BatchingOptions.BatchSizeLimit = 700;
                        options.BatchingOptions.QueueLimit = 10;
                    });
            }, preserveStaticLogger: true);
        }
```

I call this from Program.cs file. Now, when I run the program, I get the following exception. The stack trace does not help much. Can someone please explain what could be the issue?

```
Exception while emitting periodic batch from Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink: System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The response ended prematurely.
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Serilog.Sinks.OpenTelemetry.HttpExporter.ExportAsync(ExportLogsServiceRequest request)
at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
```

**Comment by nblumhardt** [comment]
Hi @sharifmamun. This looks like the kind of thing you'll see when the protocol used by client and server don't match. E.g. on the collector side, is it definitely listening using HTTP and not HTTPS? And for `http/protobuf` on that port, rather than `grpc`?

Digging into it with a tool like Wireshark will turn up some more information. HTH!

**Comment by sharifmamun** [comment]
Looks like my Open Telemetry collector was not listening to `http/protobuf` port. Thanks for your help.
